

#  application-dev.yml文件内容=============================================================================
# 配置服务端口号
server:
  port: 8501


# application.yml文件内容==================================================================================
spring:
  application:
    name: service-manager
  profiles:
    active: dev		# 激活的环境文件

  # 配置数据库连接信息
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  # Redis的相关配置
  data:
    redis:
      host: 192.168.157.133
      port: 6379
      password: 1234

#MyBatis的配置
mybatis:
  #配置Mapper映射文件存放的路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰映射
    map-underscore-to-camel-case: true
    #在控制台打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spzx:
  auth:
    noAuthUrls:
      - /doc.html
      - /webjars/css/**
      - /webjars/js/**
      - /v3/api-docs/**
      - /favicon.ico
      - /admin/system/index/login
      - /admin/system/index/getCode
  # 自定义配置

  minio:
    endpointUrl: http://localhost:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: spzx